JOBWAY/Models/Offre.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace JOBWAY.Models
{
    public class Offre
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        private int id;
        private string titre;
        private string description;
        private string image;
        private double salaire;
        private string phone;
        private string email;
        private DateTime dateTime = DateTime.Now;
        private bool isTaken = false;
        private string categorie;
        private string ville;

        public int Id { get => id; set => id = value; }
        public string Titre { get => titre; set => titre = value; }
        public string Description { get => description; set => description = value; }
        public string Image { get => image; set => image = value; }
        public double Salaire { get => salaire; set => salaire = value; }
        public string Phone { get => phone; set => phone = value; }
        public string Email { get => email; set => email = value; }
        public DateTime DateTime { get => dateTime; set => dateTime = value; }
        public bool IsTaken { get => isTaken; set => isTaken = value; }
        public string Categorie { get => categorie; set => categorie = value; }
        public string Ville { get => ville; set => ville = value; }


    }
}

JOBWAY/Controllers/OffresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JOBWAY;
using JOBWAY.Models;
using PagedList;

namespace JOBWAY.Controllers
{
    public class OffresController : Controller
    {
        private Model1 db = new Model1();

        // GET: Offres
        /**/
        public ActionResult Index(string searchString, string Categories)
        {
            var offres = from o in db.Offres
                           select o;
            if (!String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(Categories))
            {
                offres = offres.Where(s => (s.Titre.Contains(searchString)
                                       || s.Description.Contains(searchString)
                                       || s.Ville.Contains(searchString)) && s.Categorie.Contains(Categories));
            }

            List<Offre> dispoonibles = new List<Offre>();
            foreach (var o in offres.ToList())
            {
                if(o.IsTaken == false)
                {
                    dispoonibles.Add(o);
                }
            }

            ViewBag.Categories = new SelectList(
    new List<SelectListItem>
    {
        new SelectListItem { Selected = false, Text = "Informatique", Value = "Informatique"},
        new SelectListItem { Selected = false, Text = "Web", Value ="Web"},
        new SelectListItem { Selected = false, Text = "Commerce", Value ="Commerce"},


    }, "Value", "Text", 1);

            return View(dispoonibles.OrderByDescending(x => x.DateTime));
        }

        // GET: Offres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offre offre = db.Offres.Find(id);
            if (offre == null)
            {
                return HttpNotFound();
            }
            return View(offre);
        }

        // GET: Offres/Create
        public ActionResult Create()
        {
            ViewBag.Categorie = new SelectList(
   new List<SelectListItem>
   {
        new SelectListItem { Selected = false, Text = "Informatique", Value = "Informatique"},
        new SelectListItem { Selected = false, Text = "Web", Value ="Web"},
        new SelectListItem { Selected = false, Text = "Commerce", Value ="Commerce"},


   }, "Value", "Text", 1);

            return View();
        }

        // POST: Offres/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Offre offre)
        {
            ViewBag.Categorie = new SelectList(
   new List<SelectListItem>
   {
        new SelectListItem { Selected = false, Text = "Informatique", Value = "Informatique"},
        new SelectListItem { Selected = false, Text = "Web", Value ="Web"},
        new SelectListItem { Selected = false, Text = "Commerce", Value ="Commerce"},


   }, "Value", "Text", 1);
            if (ModelState.IsValid)
            {
                db.Offres.Add(offre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(offre);
        }

        // GET: Offres/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offre offre = db.Offres.Find(id);
            if (offre == null)
            {
                return HttpNotFound();
            }
            return View(offre);
        }

        // POST: Offres/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Offre offre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(offre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(offre);
        }

        // GET: Offres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offre offre = db.Offres.Find(id);
            if (offre == null)
            {
                return HttpNotFound();
            }
            return View(offre);
        }

        // POST: Offres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Offre offre = db.Offres.Find(id);
            db.Offres.Remove(offre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JOBWAY/Views/Offres/Create.cshtml
@model JOBWAY.Models.Offre

@{
    ViewBag.Title = "Create";
}


<div class="p-5 mt-5">
    <h4>Crée une nouvelle offre d'emploi</h4>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Titre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Titre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Titre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Salaire, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Salaire, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
            @Html.ValidationMessageFor(model => model.Salaire, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ville, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ville, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Ville, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Categorie, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Categorie", null, "-- Catégorie --", htmlAttributes: new { @class = "form-control produit_multi", style = "z-index:1" })
            @Html.ValidationMessageFor(model => model.Categorie, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Enregistrer" class="btn btn-primary" />
        </div>
    </div>
</div>
    }

    <div>
        @Html.ActionLink("Retour à la liste des offres", "Index")
    </div>
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

JOBWAY/Views/Offres/Delete.cshtml
@model JOBWAY.Models.Offre

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Offre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salaire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JOBWAY/Views/Offres/Details.cshtml
@model JOBWAY.Models.Offre

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Offre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salaire)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JOBWAY/Views/Offres/Edit.cshtml
@model JOBWAY.Models.Offre

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Offre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Titre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

JOBWAY/Views/Offres/Index.cshtml
@model IEnumerable<JOBWAY.Models.Offre>

@{
    ViewBag.Title = "Index";
}

<!-- Page Content -->
<div class="container">

    <!-- Page Heading -->
    <h2 class="mt-5">
        Liste des offres
    </h2>

    @using (Html.BeginForm("Index", "Offres", FormMethod.Get))
    {
        <div class="form-inline row" style="margin-top:20px;margin-bottom:20px">
            <div class="form-group col-md-4">
                @Html.TextBox("searchString", ViewBag.CurrentFilter as string, new { @class = "form-control", placeholder = "Par titre, ville ou description" })
            </div>
            <div class="form-group col-md-4">
                @Html.DropDownList("Categories", null, "Par catégorie", htmlAttributes: new { @class = "form-control produit_multi", style = "z-index:1" })
            </div>
            <div class="col-md-2">
                <input type="submit" class="btn btn-primary" value="Rechercher" />

            </div>
        </div>
    }
    @*<div class="col-md-6">
        @using (Html.BeginForm("Index", "Offres", FormMethod.Get))
        {
        <div class="form-inline row" style="margin-top:20px;margin-bottom:20px">
            <div class="form-group col-md-8">
                @Html.DropDownList("options", null, "select", htmlAttributes: new { @class = "form-control produit_multi", style = "z-index:1" })
            </div>
            <div class="col-md-4">

                <input type="submit" class="btn btn-primary mb-2" value="Search" />
                </div>
            </div>
            }

        </div>*@








    @{
        int count = 0;
    }

    @foreach (var item in Model)
    {

        count = 1;
        <!-- Project One -->
<div class="row">
    <div class="col-md-7">
       
        <a href="#">
@*            <img class="img-fluid rounded mb-3 mb-md-0" src="https://via.placeholder.com/650x300" alt="">
*@            <img class="img-fluid rounded mb-3 mb-md-0" src='~/files/@(item.Image)' alt="">

            @*            <img class="img-fluid rounded mb-3 mb-md-0" src='"~/files/"+@(item.Image)' alt="">
            *@
            @*  @if (String.IsNullOrEmpty(item.Image))
        {
            <img class="img-fluid rounded mb-3 mb-md-0" src="https://via.placeholder.com/650x300" alt="">

        }
        else
        {
            <img class="img-fluid rounded mb-3 mb-md-0" src="~/<% item.Image %>" alt="">

        }*@
        </a>
    </div>
    <div class="col-md-5">
        <h3>@Html.DisplayFor(modelItem => item.Titre)</h3>
        <p>@Html.DisplayFor(modelItem => item.Description)</p>
        <p><strong>@Html.DisplayNameFor(model => model.Email) :</strong> @Html.DisplayFor(modelItem => item.Email)</p>
        <p><strong>@Html.DisplayNameFor(model => model.Phone) :</strong> @Html.DisplayFor(modelItem => item.Phone)</p>
        <p><strong>@Html.DisplayNameFor(model => model.Salaire) :</strong> @Html.DisplayFor(modelItem => item.Salaire)</p>
        <p><strong>@Html.DisplayNameFor(model => model.Ville) :</strong> @Html.DisplayFor(modelItem => item.Ville)</p>
        <p><strong>@Html.DisplayNameFor(model => model.Categorie) :</strong> @Html.DisplayFor(modelItem => item.Categorie)</p>


        <p><strong>le :</strong> @Html.DisplayFor(modelItem => item.DateTime)</p>
        @Html.ActionLink("View Project", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
    </div>
</div>
        <!-- /.row -->
        <hr>
    }

    @{
        if (count == 0)
        {
            <h2>Il n'y a pas des offres disponibles</h2>
        }
    }
    <p>
        @Html.ActionLink("Crée un nouveau offre", "Create")
    </p>

</div>